#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KINO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
using System.IO;
using System.IO.IsolatedStorage;
using Microsoft.Phone.Data.Linq.Mapping;
using Microsoft.Phone.Data.Linq;


public class DebugWriter : TextWriter
{
    private const int DefaultBufferSize = 256;
    private System.Text.StringBuilder _buffer;

    public DebugWriter()
    {
        BufferSize = 256;
        _buffer = new System.Text.StringBuilder(BufferSize);
    }

    public int BufferSize
    {
        get;
        private set;
    }

    public override System.Text.Encoding Encoding
    {
        get { return System.Text.Encoding.UTF8; }
    }

    #region StreamWriter Overrides
    public override void Write(char value)
    {
        _buffer.Append(value);
        if (_buffer.Length >= BufferSize)
            Flush();
    }

    public override void WriteLine(string value)
    {
        Flush();

        using(var reader = new StringReader(value))
        {
            string line; 
            while( null != (line = reader.ReadLine()))
                System.Diagnostics.Debug.WriteLine(line);
        }
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
            Flush();
    }

    public override void Flush()
    {
        if (_buffer.Length > 0)
        {
            System.Diagnostics.Debug.WriteLine(_buffer);
            _buffer.Clear();
        }
    }
    #endregion
}


	public partial class MMA_kinoContext : System.Data.Linq.DataContext
	{
		
		public bool CreateIfNotExists()
		{
			bool created = false;
			if (!this.DatabaseExists())
			{
				string[] names = this.GetType().Assembly.GetManifestResourceNames();
				string name = names.Where(n => n.EndsWith(FileName)).FirstOrDefault();
				if (name != null)
				{
					using (Stream resourceStream = Assembly.GetExecutingAssembly().GetManifestResourceStream(name))
					{
						if (resourceStream != null)
						{
							using (IsolatedStorageFile myIsolatedStorage = IsolatedStorageFile.GetUserStoreForApplication())
							{
								using (IsolatedStorageFileStream fileStream = new IsolatedStorageFileStream(FileName, FileMode.Create, myIsolatedStorage))
								{
									using (BinaryWriter writer = new BinaryWriter(fileStream))
									{
										long length = resourceStream.Length;
										byte[] buffer = new byte[32];
										int readCount = 0;
										using (BinaryReader reader = new BinaryReader(resourceStream))
										{
											// read file in chunks in order to reduce memory consumption and increase performance
											while (readCount < length)
											{
												int actual = reader.Read(buffer, 0, buffer.Length);
												readCount += actual;
												writer.Write(buffer, 0, actual);
											}
										}
									}
								}
							}
							created = true;
						}
						else
						{
							this.CreateDatabase();
							created = true;
						}
					}
				}
				else
				{
					this.CreateDatabase();
					created = true;
				}
			}
			return created;
		}
		
		public bool LogDebug
		{
			set
			{
				if (value)
				{
					this.Log = new DebugWriter();
				}
			}
		}
		
		public static string ConnectionString = "Data Source=isostore:/MMA_kino.sdf";

		public static string ConnectionStringReadOnly = "Data Source=appdata:/MMA_kino.sdf;File Mode=Read Only;";

		public static string FileName = "MMA_kino.sdf";

		public MMA_kinoContext(string connectionString) : base(connectionString)
		{
			OnCreated();
		}
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCet_Sala1(Cet_Sala1 instance);
    partial void UpdateCet_Sala1(Cet_Sala1 instance);
    partial void DeleteCet_Sala1(Cet_Sala1 instance);
    partial void InsertNed_Sala1(Ned_Sala1 instance);
    partial void UpdateNed_Sala1(Ned_Sala1 instance);
    partial void DeleteNed_Sala1(Ned_Sala1 instance);
    partial void InsertPet_Sala1(Pet_Sala1 instance);
    partial void UpdatePet_Sala1(Pet_Sala1 instance);
    partial void DeletePet_Sala1(Pet_Sala1 instance);
    partial void InsertPon_Sala1(Pon_Sala1 instance);
    partial void UpdatePon_Sala1(Pon_Sala1 instance);
    partial void DeletePon_Sala1(Pon_Sala1 instance);
    partial void InsertSri_Sala1(Sri_Sala1 instance);
    partial void UpdateSri_Sala1(Sri_Sala1 instance);
    partial void DeleteSri_Sala1(Sri_Sala1 instance);
    partial void InsertSub_Sala1(Sub_Sala1 instance);
    partial void UpdateSub_Sala1(Sub_Sala1 instance);
    partial void DeleteSub_Sala1(Sub_Sala1 instance);
    partial void InsertUto_Sala1(Uto_Sala1 instance);
    partial void UpdateUto_Sala1(Uto_Sala1 instance);
    partial void DeleteUto_Sala1(Uto_Sala1 instance);
    #endregion
		
		public System.Data.Linq.Table<Cet_Sala1> Cet_Sala1
		{
			get
			{
				return this.GetTable<Cet_Sala1>();
			}
		}
		
		public System.Data.Linq.Table<Ned_Sala1> Ned_Sala1
		{
			get
			{
				return this.GetTable<Ned_Sala1>();
			}
		}
		
		public System.Data.Linq.Table<Pet_Sala1> Pet_Sala1
		{
			get
			{
				return this.GetTable<Pet_Sala1>();
			}
		}
		
		public System.Data.Linq.Table<Pon_Sala1> Pon_Sala1
		{
			get
			{
				return this.GetTable<Pon_Sala1>();
			}
		}
		
		public System.Data.Linq.Table<Sri_Sala1> Sri_Sala1
		{
			get
			{
				return this.GetTable<Sri_Sala1>();
			}
		}
		
		public System.Data.Linq.Table<Sub_Sala1> Sub_Sala1
		{
			get
			{
				return this.GetTable<Sub_Sala1>();
			}
		}
		
		public System.Data.Linq.Table<Uto_Sala1> Uto_Sala1
		{
			get
			{
				return this.GetTable<Uto_Sala1>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Cet-sala1")]
	public partial class Cet_Sala1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Naziv;
		
		private int _Cijena;
		
		private string _Termin;
		
		private System.Data.Linq.Binary _Slika;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNazivChanging(string value);
    partial void OnNazivChanged();
    partial void OnCijenaChanging(int value);
    partial void OnCijenaChanged();
    partial void OnTerminChanging(string value);
    partial void OnTerminChanged();
    partial void OnSlikaChanging(System.Data.Linq.Binary value);
    partial void OnSlikaChanged();
    #endregion
		
		public Cet_Sala1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naziv", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Naziv
		{
			get
			{
				return this._Naziv;
			}
			set
			{
				if ((this._Naziv != value))
				{
					this.OnNazivChanging(value);
					this.SendPropertyChanging();
					this._Naziv = value;
					this.SendPropertyChanged("Naziv");
					this.OnNazivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cijena", DbType="Int NOT NULL")]
		public int Cijena
		{
			get
			{
				return this._Cijena;
			}
			set
			{
				if ((this._Cijena != value))
				{
					this.OnCijenaChanging(value);
					this.SendPropertyChanging();
					this._Cijena = value;
					this.SendPropertyChanged("Cijena");
					this.OnCijenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Termin", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Termin
		{
			get
			{
				return this._Termin;
			}
			set
			{
				if ((this._Termin != value))
				{
					this.OnTerminChanging(value);
					this.SendPropertyChanging();
					this._Termin = value;
					this.SendPropertyChanged("Termin");
					this.OnTerminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Slika", DbType="Image NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Slika
		{
			get
			{
				return this._Slika;
			}
			set
			{
				if ((this._Slika != value))
				{
					this.OnSlikaChanging(value);
					this.SendPropertyChanging();
					this._Slika = value;
					this.SendPropertyChanged("Slika");
					this.OnSlikaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Ned-sala1")]
	public partial class Ned_Sala1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Naziv;
		
		private int _Cijena;
		
		private string _Termin;
		
		private System.Data.Linq.Binary _Slika;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNazivChanging(string value);
    partial void OnNazivChanged();
    partial void OnCijenaChanging(int value);
    partial void OnCijenaChanged();
    partial void OnTerminChanging(string value);
    partial void OnTerminChanged();
    partial void OnSlikaChanging(System.Data.Linq.Binary value);
    partial void OnSlikaChanged();
    #endregion
		
		public Ned_Sala1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naziv", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Naziv
		{
			get
			{
				return this._Naziv;
			}
			set
			{
				if ((this._Naziv != value))
				{
					this.OnNazivChanging(value);
					this.SendPropertyChanging();
					this._Naziv = value;
					this.SendPropertyChanged("Naziv");
					this.OnNazivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cijena", DbType="Int NOT NULL")]
		public int Cijena
		{
			get
			{
				return this._Cijena;
			}
			set
			{
				if ((this._Cijena != value))
				{
					this.OnCijenaChanging(value);
					this.SendPropertyChanging();
					this._Cijena = value;
					this.SendPropertyChanged("Cijena");
					this.OnCijenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Termin", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Termin
		{
			get
			{
				return this._Termin;
			}
			set
			{
				if ((this._Termin != value))
				{
					this.OnTerminChanging(value);
					this.SendPropertyChanging();
					this._Termin = value;
					this.SendPropertyChanged("Termin");
					this.OnTerminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Slika", DbType="Image NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Slika
		{
			get
			{
				return this._Slika;
			}
			set
			{
				if ((this._Slika != value))
				{
					this.OnSlikaChanging(value);
					this.SendPropertyChanging();
					this._Slika = value;
					this.SendPropertyChanged("Slika");
					this.OnSlikaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Pet-sala1")]
	public partial class Pet_Sala1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Naziv;
		
		private int _Cijena;
		
		private string _Termin;
		
		private System.Data.Linq.Binary _Slika;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNazivChanging(string value);
    partial void OnNazivChanged();
    partial void OnCijenaChanging(int value);
    partial void OnCijenaChanged();
    partial void OnTerminChanging(string value);
    partial void OnTerminChanged();
    partial void OnSlikaChanging(System.Data.Linq.Binary value);
    partial void OnSlikaChanged();
    #endregion
		
		public Pet_Sala1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naziv", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Naziv
		{
			get
			{
				return this._Naziv;
			}
			set
			{
				if ((this._Naziv != value))
				{
					this.OnNazivChanging(value);
					this.SendPropertyChanging();
					this._Naziv = value;
					this.SendPropertyChanged("Naziv");
					this.OnNazivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cijena", DbType="Int NOT NULL")]
		public int Cijena
		{
			get
			{
				return this._Cijena;
			}
			set
			{
				if ((this._Cijena != value))
				{
					this.OnCijenaChanging(value);
					this.SendPropertyChanging();
					this._Cijena = value;
					this.SendPropertyChanged("Cijena");
					this.OnCijenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Termin", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Termin
		{
			get
			{
				return this._Termin;
			}
			set
			{
				if ((this._Termin != value))
				{
					this.OnTerminChanging(value);
					this.SendPropertyChanging();
					this._Termin = value;
					this.SendPropertyChanged("Termin");
					this.OnTerminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Slika", DbType="Image NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Slika
		{
			get
			{
				return this._Slika;
			}
			set
			{
				if ((this._Slika != value))
				{
					this.OnSlikaChanging(value);
					this.SendPropertyChanging();
					this._Slika = value;
					this.SendPropertyChanged("Slika");
					this.OnSlikaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Pon-sala1")]
	public partial class Pon_Sala1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Naziv;
		
		private System.Data.Linq.Binary _Slika;
		
		private System.Nullable<int> _Cijena;
		
		private string _Termin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNazivChanging(string value);
    partial void OnNazivChanged();
    partial void OnSlikaChanging(System.Data.Linq.Binary value);
    partial void OnSlikaChanged();
    partial void OnCijenaChanging(System.Nullable<int> value);
    partial void OnCijenaChanged();
    partial void OnTerminChanging(string value);
    partial void OnTerminChanged();
    #endregion
		
		public Pon_Sala1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naziv", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Naziv
		{
			get
			{
				return this._Naziv;
			}
			set
			{
				if ((this._Naziv != value))
				{
					this.OnNazivChanging(value);
					this.SendPropertyChanging();
					this._Naziv = value;
					this.SendPropertyChanged("Naziv");
					this.OnNazivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Slika", DbType="Image NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Slika
		{
			get
			{
				return this._Slika;
			}
			set
			{
				if ((this._Slika != value))
				{
					this.OnSlikaChanging(value);
					this.SendPropertyChanging();
					this._Slika = value;
					this.SendPropertyChanged("Slika");
					this.OnSlikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cijena", DbType="Int")]
		public System.Nullable<int> Cijena
		{
			get
			{
				return this._Cijena;
			}
			set
			{
				if ((this._Cijena != value))
				{
					this.OnCijenaChanging(value);
					this.SendPropertyChanging();
					this._Cijena = value;
					this.SendPropertyChanged("Cijena");
					this.OnCijenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Termin", DbType="NVarChar(25)")]
		public string Termin
		{
			get
			{
				return this._Termin;
			}
			set
			{
				if ((this._Termin != value))
				{
					this.OnTerminChanging(value);
					this.SendPropertyChanging();
					this._Termin = value;
					this.SendPropertyChanged("Termin");
					this.OnTerminChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Sri-sala1")]
	public partial class Sri_Sala1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Naziv;
		
		private int _Cijena;
		
		private string _Termin;
		
		private System.Data.Linq.Binary _Slika;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNazivChanging(string value);
    partial void OnNazivChanged();
    partial void OnCijenaChanging(int value);
    partial void OnCijenaChanged();
    partial void OnTerminChanging(string value);
    partial void OnTerminChanged();
    partial void OnSlikaChanging(System.Data.Linq.Binary value);
    partial void OnSlikaChanged();
    #endregion
		
		public Sri_Sala1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naziv", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Naziv
		{
			get
			{
				return this._Naziv;
			}
			set
			{
				if ((this._Naziv != value))
				{
					this.OnNazivChanging(value);
					this.SendPropertyChanging();
					this._Naziv = value;
					this.SendPropertyChanged("Naziv");
					this.OnNazivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cijena", DbType="Int NOT NULL")]
		public int Cijena
		{
			get
			{
				return this._Cijena;
			}
			set
			{
				if ((this._Cijena != value))
				{
					this.OnCijenaChanging(value);
					this.SendPropertyChanging();
					this._Cijena = value;
					this.SendPropertyChanged("Cijena");
					this.OnCijenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Termin", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Termin
		{
			get
			{
				return this._Termin;
			}
			set
			{
				if ((this._Termin != value))
				{
					this.OnTerminChanging(value);
					this.SendPropertyChanging();
					this._Termin = value;
					this.SendPropertyChanged("Termin");
					this.OnTerminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Slika", DbType="Image NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Slika
		{
			get
			{
				return this._Slika;
			}
			set
			{
				if ((this._Slika != value))
				{
					this.OnSlikaChanging(value);
					this.SendPropertyChanging();
					this._Slika = value;
					this.SendPropertyChanged("Slika");
					this.OnSlikaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Sub-sala1")]
	public partial class Sub_Sala1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Naziv;
		
		private int _Cijena;
		
		private string _Termin;
		
		private System.Data.Linq.Binary _Slika;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNazivChanging(string value);
    partial void OnNazivChanged();
    partial void OnCijenaChanging(int value);
    partial void OnCijenaChanged();
    partial void OnTerminChanging(string value);
    partial void OnTerminChanged();
    partial void OnSlikaChanging(System.Data.Linq.Binary value);
    partial void OnSlikaChanged();
    #endregion
		
		public Sub_Sala1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naziv", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Naziv
		{
			get
			{
				return this._Naziv;
			}
			set
			{
				if ((this._Naziv != value))
				{
					this.OnNazivChanging(value);
					this.SendPropertyChanging();
					this._Naziv = value;
					this.SendPropertyChanged("Naziv");
					this.OnNazivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cijena", DbType="Int NOT NULL")]
		public int Cijena
		{
			get
			{
				return this._Cijena;
			}
			set
			{
				if ((this._Cijena != value))
				{
					this.OnCijenaChanging(value);
					this.SendPropertyChanging();
					this._Cijena = value;
					this.SendPropertyChanged("Cijena");
					this.OnCijenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Termin", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Termin
		{
			get
			{
				return this._Termin;
			}
			set
			{
				if ((this._Termin != value))
				{
					this.OnTerminChanging(value);
					this.SendPropertyChanging();
					this._Termin = value;
					this.SendPropertyChanged("Termin");
					this.OnTerminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Slika", DbType="Image NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Slika
		{
			get
			{
				return this._Slika;
			}
			set
			{
				if ((this._Slika != value))
				{
					this.OnSlikaChanging(value);
					this.SendPropertyChanging();
					this._Slika = value;
					this.SendPropertyChanged("Slika");
					this.OnSlikaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Uto-sala1")]
	public partial class Uto_Sala1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Naziv;
		
		private int _Cijena;
		
		private string _Termin;
		
		private System.Data.Linq.Binary _Slika;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNazivChanging(string value);
    partial void OnNazivChanged();
    partial void OnCijenaChanging(int value);
    partial void OnCijenaChanged();
    partial void OnTerminChanging(string value);
    partial void OnTerminChanged();
    partial void OnSlikaChanging(System.Data.Linq.Binary value);
    partial void OnSlikaChanged();
    #endregion
		
		public Uto_Sala1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naziv", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Naziv
		{
			get
			{
				return this._Naziv;
			}
			set
			{
				if ((this._Naziv != value))
				{
					this.OnNazivChanging(value);
					this.SendPropertyChanging();
					this._Naziv = value;
					this.SendPropertyChanged("Naziv");
					this.OnNazivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cijena", DbType="Int NOT NULL")]
		public int Cijena
		{
			get
			{
				return this._Cijena;
			}
			set
			{
				if ((this._Cijena != value))
				{
					this.OnCijenaChanging(value);
					this.SendPropertyChanging();
					this._Cijena = value;
					this.SendPropertyChanged("Cijena");
					this.OnCijenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Termin", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Termin
		{
			get
			{
				return this._Termin;
			}
			set
			{
				if ((this._Termin != value))
				{
					this.OnTerminChanging(value);
					this.SendPropertyChanging();
					this._Termin = value;
					this.SendPropertyChanged("Termin");
					this.OnTerminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Slika", DbType="Image NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Slika
		{
			get
			{
				return this._Slika;
			}
			set
			{
				if ((this._Slika != value))
				{
					this.OnSlikaChanging(value);
					this.SendPropertyChanging();
					this._Slika = value;
					this.SendPropertyChanged("Slika");
					this.OnSlikaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
